services:
  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:10.45.1c
    container_name: ib-gateway
    environment:
      - TWS_USERID=${IBKR_USER}
      - TWS_PASSWORD=${IBKR_PASSWORD}
      - TRADING_MODE=paper
      - TWS_ACCEPT_INCOMING=127.0.0.1,172.0.0.0/8
      - BYPASS_LOCALHOST_WARNING=yes   
      - READ_ONLY_API=no          
    ports:
      - "4004:4004"
    restart: always

  trading-bot:
    build: .
    container_name: trading-bot
    depends_on:
      - ib-gateway
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - IBKR_HOST=ib-gateway
      - IBKR_PORT=4004
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always                                   